### ISSUE TITLE
how to force prerendering from the command line?

### ISSUE THREAD

**Issue by indiamcq** [microlinkhq/html-get#114]
One my machine HTML-GET is prerendering JavaScript to HTML. Which is what I want.
But on a colleagues machine it is not prerendering the JavaScript.

On the command line how do I force the prerendering? Or do I need to make a script adjustment some where? If so then where specifically. I am only a NPM command line user not a JavaScripter, so need very specific directions.

**Comment by Kikobeats** [comment]
Hello,

I released an `html-get@2.8.24` that adds support for passing flags at CLI.

The command run have to run is:

```bash
npx html-get https://example.com --prerender
```
