### ISSUE TITLE
The 'Chromium' process stay alive even after getHTML is done

### ISSUE THREAD

**Issue by rkdrns4747** [microlinkhq/html-get#135]
The 'Chromium' process stay alive even after getHTML is done(shows up on task manager). It's ok if it does nothing and just stay alive , but it takes so much CPU resource.

Is there any way to automatically close chromium after getHTML function has done?

**Comment by Kikobeats** [comment]
Hello,

Thanks for reporting. I added a more complete example showcasing how you can control the Chromium process lifecycle:

https://github.com/microlinkhq/html-get#usage=
