### ISSUE TITLE
How to use Firefox instead of chrome

### ISSUE THREAD

**Issue by athrvk** [microlinkhq/html-get#203]
Is there a documentation on how to use firefox, instead of chrome?

i tried this

```
getHTML(url, {
        getBrowserless, rewriteUrls: true, puppeteerOpts: {
            product: 'firefox'
        }
    })
```
is this correct or any other way to use it ?

**Comment by Kikobeats** [comment]
Hey, check puppeteer docs https://pptr.dev/faq/#q-which-firefox-version-does-puppeteer-use 🙂
