### ISSUE TITLE
returned html structure not complete

### ISSUE THREAD

**Issue by AndrejGajdos** [microlinkhq/html-get#55]
If I try to get html structure by:

```
(async () => {
  const { url, html, stats } = await getHTML('https://www.thewashingtondailynews.com/2019/09/04/early-voting-ends-early-in-advance-of-dorian/');
  console.log(html)
})()
```

Returned html structure is not complete, for example it doesn't contain `og:description` tag.

[Result](https://pastebin.com/XYLkFFRV)

**Comment by Kikobeats** [comment]
sorry for that but the pastebin expired, I can't reproduce it

**Comment by Kikobeats** [comment]
If you perform

```
npx html-get https://www.thewashingtondailynews.com/2019/09/04/early-voting-ends-early-in-advance-of-dorian
```

I can see `og:description` on the payload, so I'm going to consider this a temporal behavior happened in the past probably related with the server origin, not with the library itself.
