### ISSUE TITLE
Resolve CloudFlare DDoS challenge

### ISSUE THREAD

**Issue by Kikobeats** [microlinkhq/html-get#77]
- https://github.com/sayem314/hooman
- https://github.com/TypeCtrl/cloudflare (slow)
- https://github.com/codemanki/cloudscraper (unmaintained)
- https://github.com/k4m4/cloudflare-detect (too basic)

**Comment by trendchaser4u** [comment]
Hello @Kikobeats ,

Any plan to add **bypass-cloudflare** challenge feature in the upcoming release? In the meantime could you please guide us on how you integrated the solution in Microlink API. I used this link    https://9gag.com/gag/aEgr1yK to test with the above-mentioned solution. I couldn't achieve a complete solution, sometimes the site throwing captcha error. 
It would be very helpful if you help me with this. thanks.

**Comment by Kikobeats** [comment]
@trendchaser4u soon 🙂
