### ISSUE TITLE
Resolve relative URLS getting changed to absolute URLS

### ISSUE THREAD

**Issue by manpreet2760** [microlinkhq/html-get#92]
Hello,

I am currently using that package for one of my work and facing an issue that relative URLs in HTML are getting resolved to absolute URLs.

URL: https://spiritualtactics.com/

After some trial and error found out that if the following function in index.js (Line : 140)
rewriteHtmlUrls({ $, url, headers })

is comment out then the downloaded HTML contains relative URLs. 

Request your assistance in solving this issue. As I want to have the downloaded HTML unmodified i.e. if the URLs in the original HTML is absolute it should be absolute else if it is relative, then the downloaded should have relative.

Thanks

**Comment by Kikobeats** [comment]
Hello,

I added `rewriteUrls` parameter for enabling the ability to rewrite relative to absolute URLs.

It's `false` by default, so if you use the latest version, your problem should be fixed and you don't need to do anything additional 🙂
