### ISSUE TITLE
MaxListenersExceededWarning

### ISSUE THREAD

**Issue by micheledallerive** [microlinkhq/html-get#99]
I'm trying to figure out why I keep getting this error:
```
(node:22272) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
(node:22272) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added. Use emitter.setMaxListeners() to increase limit
(node:22272) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added. Use emitter.setMaxListeners() to increase limit
(node:22272) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGHUP listeners added. Use emitter.setMaxListeners() to increase limit
```

To be honest I'm quite new in NodeJS coding but I found online that this error is caused by too many listeners being attached to a EventEmitter. I don't know how to solve this, but I'm quite sure it's caused by this module because removing it everything works fine.
This is my code:
```
getHTML(url)
        .then(({url, html, stats, headers, statusCode})=>{
            if(statusCode==200){
                console.log(statusCode);
            }
        })
        .catch((err)=>{
            onCheckError(err);
        });
```
It is executed every 5 seconds.

**Comment by Kikobeats** [comment]
I tried to reproduce the Error with no success.

That's strange; what's version of Node.js are you using?

**Comment by micheledallerive** [comment]
Maybe you did not get the error because you ran it  once. I execute it every 5 seconds and I get the error at the 5th time it is executed. My node version is 10.16.0.

**Comment by Kikobeats** [comment]
Can you try node version 12?
